package com.healthifyme.android.init;

public interface TestDataCoulmns {

	/** FARMERS SHEET HEADINGS **/
	
	String TEST_CASE_NO="TEST_CASE_NO";
	String FARMER_NAME="FARMER_NAME";
	String FARMER_ID="FARMER_ID";
	String FARMER_BARCODE="FARMER_BARCODE";
	String NUM_OF_CANS="NUM_OF_CANS";
	String CATTLE_TYPE="CATTLE_TYPE";
	String SOCIETY_CODE="SOCIETY_CODE";
	String MOBILE="MOBILE";
	String NUM_OF_COWS="NUM_OF_COWS";
	String NUM_OF_BUFFALOS="NUM_OF_BUFFALOS";
	String COW_HERD_SIZE="COW_HERD_SIZE";
	String BUFFALO_HERD_SIZE="BUFFALO_HERD_SIZE";
	String NUM_OF_FAMILY="NUM_OF_FAMILY";
	String DAIRY_INCOME_PRIMARY="DAIRY_INCOME_PRIMARY";
	String DAIRY_INCOME_SECONDARY="DAIRY_INCOME_SECONDARY";
	String PRIMARY_INCOME="PRIMARY_INCOME";
	String FARMER_AGE="FARMER_AGE";
	String FARMER_EDUCATION="FARMER_EDUCATION";
	String FARMER_GENDER="FARMER_GENDER";
	String FARMER_ADDRESS="FARMER_ADDRESS";
	String REGION="REGION";
	String PINCODE="PINCODE";
	String FARMER_ECS_CODE="ECS CODE";
	String FARMER_CATEGORY="CATEGORY";
	
	/** PORTAL **/
	
	String UNIQUE_CODE="UNIQUE_CODE";
	String MULTIPLE_CANS="MULTIPLE_CANS";
	String PRODUCER_TYPE="PRODUCER_TYPE";
	
	
	
	/** CONFIGURATION SHEET HEADINGS **/
	
	String MILK_ANALYZER="MILK_ANALYZER";
	String MILK_ANLYZ_BUDRATE="MILK_ANLYZ_BUDRATE";
	String PRINTER="PRINTER";
	String PRINTER_BUDRATE="PRINTER_BUDRATE";
	String RDU="RDU";
	String RDU_BUDRATE="RDU_BUDRATE";
	String PREFFIX="PREFFIX";
	String SUFFIX="SUFFIX";
	String WEIGHING_MACHINE="WEIGHING_MACHINE";
	String WEIGHING_BUDRATE="WEIGHING_BUDRATE";
	String SCALE_LIMIT="SCALE_LIMIT";
	String FAT="FAT";
	String SNF="SNF";
	String QTY="QTY";
	String CHILLING_CENTER="CHILLING_CENTER";
	String COLLECTION_CENTER="COLLECTION_CENTER";
	String REPORT_TYPE="REPORT_TYPE";
	String FARMERS_SHEET="Farmers";
	String CONFIG_SHEET="Configuration";
	String MA_CONFIG_TYPE="MA_CONFIG_TYPE";
	
	/** FARMER_TEMPLATE SAMPLESHEET HEADINGS **/
	
	String FAR_TEMP_SHEET="Sample_Template";
	String FAR_TEMP_FARMER_ID="Farmer Id";
	String FAR_TEMP_FARMER_NAME="First Name";
	String FAR_TEMP_FARMER_MOBILE="Mobile Number";
	String FAR_TEMP_FARMER_BARCODE="Barcode";
	String FAR_TEMP_MILK_TYPE="Milk Type";
	
	/**Milk Collections Sheet Headings  **/
	String MILK_COLLECTION_SHEET = "Milk Collection";
	String MILK_COLL_SCAN_MODE = "Scan_Mode";
	String MLK_COLL_FARMER_NAME="FARMER_NAME";
	String MLK_COLL_FARMER_ID="FARMER_ID";
	String MLK_COLL_FARMER_BARCODE="FARMER_BARCODE";
	String MLK_COLL_FAT="Fat";
	String MLK_COLL_SNF="SNF";
	String MLK_COLL_QTYLTRS="Qty(ltrs)";
	String MLK_COLL_RATE="Rate";
	String MLK_COLL_AMOUNT="Amount";
	
	/**Push Configuration Sheet Headings **/
	String PUSH_CONFIGURATION_SHEET = "Push Configuration";
	String PUSH_CONF_TESTCASENO = "TestCaseNo";
	String PUSH_CONF_ELEMENT ="Element";
	String PUSH_CONF_VALUE = "Value";
	String PUSH_CONF_TYPE = "Type";
	
	/**Input Test Data Configuration Sheet Headings **/
	String TEST_CASE_INPUT_DATA_CONFIG_SHEET = "TestCaseInputDataConfig";
	
	/**Test Records Sheet Headings **/
	String TEST_RECORDS_SHEET = "Test Records";
	String TEST_RECORD_ID = "TESTRECORD_ID";
	String TEST_RECORD_NAME = "TESTRECORD_NAME";
	String TEST_RECORD_FAT = "TESTRECORD_FAT";
	String TEST_RECORD_SNF = "TESTRECORD_SNF";
	String TEST_RECORD_QTY = "TESTRECORD_QTY";
	String TEST_RECORD_CATTLE_TYPE = "TESTRECORD_CATTLE_TYPE";
	
	/** IndividualReports **/
	
	String INDIVIDUAL_COLLECTION_CENTER_REPORT_SHEET = "IndividualCollectionCenterReport";
	String ICOLCENTCREPORT_START_DATE = "START DATE";
	String ICOLCENTCREPORT_END_DATE = "END DATE";
	
	
	/** Push Rate Chart **/
	
	String PUSH_RATE_CHART_SHEET = "Push Rate Chart";
	String MILK_TYPE = "Milk_Type";
	String RATE_CHART = "Rate_Chart";
	
	
	/** Sales **/
	String SALES_SHEET = "Sales";
	String SALES_NAME = "NAME";
	String SALES_CATTLE_TYPE = "CATTLE_TYPE";
	String SALES_QUANTITY = "QUANTITY";
	
	
/** CREATE CHILLING CENTER HEADINGS */
	
	String CC_SHEET_NAME="ChillingCenter";
	String CC_UNIQUE_CODE="CC_UNIQUE_CODE";
	String CC_ID="CC_ID";
	String CC_NAME="CC_NAME";
	String CENTER_TYPE="CENTER_TYPE";
	String CC_ADDR_LINE_1="CC_ADDR_LINE_1";
	String CC_ADDR_LINE_2="CC_ADDR_LINE_2";
	String LATITUDE="LATITUDE";
	String LANGITUDE="LANGITUDE";
	String ANLYS_USER_NAME="ANLYS_USER_NAME";
	String WEIG_USER_NAME="WEIG_USER_NAME";
	String CONT_PERSON_NAME="CONT_PERSON_NAME";
	String CONT_PERSON_EMAIL="CONT_PERSON_EMAIL";
	String CONT_PERSON_PHONE="CONT_PERSON_PHONE";
	String CC_TOWN="CC_TOWN";
	String CC_STATE="CC_STATE";
	String CC_DISTRICT="CC_DISTRICT";
	String CC_TALUK="CC_TALUK";
	String CC_ORGANIZATION="CC_ORGANIZATION";
	String CC_PLANT="CC_PLANT";
	String CC_IS_DEPLOYED="CC_IS_DEPLOYED";
	String CC_UOM="CC_UOM";
	String CC_CONV_FACTOR="CC_CONV_FACTOR";
	String CC_IS_COLL_CENTER="CC_IS_COLL_CENTER";
	String CC_ENABLE_SMS="CC_ENABLE_SMS";
	String CC_ACTIVATE="CC_ACTIVATE";
	
	/** CC RATE CHARTS CREATION/PUSH **/
	
	String CC_RATECHART_MATRIX_SHEET="ccratechartmatrix";
	String CC_RATECHART_NAME="CC_RATECHART_NAME";
	String CC_MILK_TYPE="CC_MILK_TYPE";
	String CC_RATECHART_TYPE="CC_RATECHART_TYPE";
	String CC_QLTY_CATEGORY="QLTY_CATEGORY";
	String CC_PAYMENT_MODE="CC_PAYMENT_MODE";
	String CC_RATECHART_CATEGORY="CC_RATECHART_CATEGORY";
	String CC_UNIT_OF_RATE="CC_UNIT_OF_RATE";
	String CC_RATECHART_ORGANIZATION="CC_RATECHART_ORGANIZATION";
	
	/** CC Test Records **/
	
	String CC_TESTRECORDS_SHEET="cctestrecords";
	
	/** Import CCs TestData Sheet Values */
	
	String SAMPLE_TEMPLATE_SHEET="Sample_Template";
	String SAMPLE_CC_ID="Collection Center ID";
	String SAMPLE_CC_NAME="Center Name";
	String SAMPLE_CC_LOCATION="Location";
	
	
	
	
	
}
